platform :ios, '8.0'
target "CompanyProjectOC" do 
pod 'AFNetworking', '~> 3.2.0'
pod 'Masonry', '~> 1.0.2'
pod 'SVProgressHUD', '~> 2.2.2'
pod 'MJRefresh', '~> 3.1.15.1'
pod 'SDAutoLayout', '~> 2.2.0'
pod 'FMDB', '~> 2.7.2'
pod 'YPTabBarController', '~> 2.4.5'
pod 'ReactiveObjC', '~> 3.0.0'
pod 'CYLTabBarController', '~> 1.17.6'
pod 'SDWebImage', '~> 4.1.0'
pod 'IQKeyboardManager', '~> 4.0.13’
pod 'Mantle', '~> 2.1.0'
pod 'YYKit', '~> 1.0.9'
pod 'JRSwizzle', '~> 1.0'
pod 'Reachability', '~> 3.2'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'HUPhotoBrowser', '~> 1.3.1'
pod 'SDCycleScrollView', '~> 1.75'
pod 'CWLateralSlide', '~> 1.4.0'
pod 'JDStatusBarNotification', '~> 1.5.6'
pod 'BButton', '~> 4.0.2'
pod 'BlocksKit', '~> 2.2.5'
pod 'MGSwipeTableCell', '~> 1.6.6'
pod 'Appirater', '~> 2.3.1'
pod 'JKCategories', '~> 1.6'
pod 'JazzHands', '~> 2.0.8'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'EAIntroView', '~> 2.12.0'
pod 'DeepLinkKit', '~> 1.4.0'
pod 'GVUserDefaults', '~> 1.0.2'
pod 'LinqToObjectiveC', '~> 2.1.0'
pod 'PNChart', '~> 0.8.9'
pod 'JCAlertController', '~> 2.2.1'
pod 'MDRadialProgress', '~> 1.3.2'
pod 'PIXFeSpinner', '~> 1.0.2'
pod 'DateTools', '~> 2.0.0'
pod 'JHChainableAnimations', '~> 3.0.1'
pod 'YTKNetwork', '~> 2.0.4'
pod 'mob_sharesdk'
pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'
pod 'mob_sharesdk/ShareSDKPlatforms/AliPaySocial'
pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
pod 'BaiduMapKit', '~> 3.4.4'
pod 'WMPageController', '~> 2.5.2'
pod 'BRPickerView', '~> 2.1.0'
pod 'JPush'
pod 'TYCyclePagerView'
end
