platform :ios, '8.0'
target "CompanyProjectOC" do 
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry', '~> 1.0.2'
pod 'SVProgressHUD', '~> 2.2.2'
pod 'MJRefresh', '~> 3.1.15.1'
pod 'SDAutoLayout', '~> 2.2.0'
pod 'FMDB', '~> 2.7.2'
pod 'YPTabBarController', '~> 2.4.4'
pod 'ReactiveObjC', '~> 3.0.0'
pod 'CYLTabBarController', '~> 1.14.2'
pod 'SDWebImage', '~> 4.1.0'
pod 'IQKeyboardManager', '~> 4.0.13’
pod 'Mantle', '~> 2.1.0'
pod 'YYKit', '~> 1.0.9'
pod 'JRSwizzle', '~> 1.0'
pod 'Reachability', '~> 3.2'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'HUPhotoBrowser', '~> 1.3.1'
pod 'SDCycleScrollView', '~> 1.74'
end
